import { env } from "@/config/env";
import { ApiError } from "@/lib/api/errors";
import { api } from "@/lib/api/client";
import { authStorage } from "@/lib/storage/auth-storage";

import type {
    AdminActivity,
    AdminAssessment,
    AdminAssessmentAttempt,
    AdminAssessmentDetail,
    AdminBroadcast,
    AdminCourse,
    AdminDashboard,
    AdminDiagnosticAnalytics,
    AdminDiagnosticRow,
    AdminDiagnosticScenarioDetail,
    AdminEnrollment,
    AdminInstructor,
    AdminQuiz,
    AdminQuizAttempt,
    AdminQuizDetail,
    AdminSimulatorAnalytics,
    AdminSimulatorSessionsPage,
    AdminStudent,
    AdminStudentJourney,
    AdminSupportTicket,
    AdminSupportTicketDetail,
    AdminUser,
    AnalyticsResponse,
    AuditSummary,
    CommerceInvoiceRow,
    CommerceOrderRow,
    CommerceOverview,
    CommercePayoutRow,
    CommerceRefundRow,
    CommerceSubscriptionRow,
    CommerceTransactionRow,
    CommerceWebhookRow,
    CrmRange,
    CrmStats,
    FailedControlRow,
    FailedPaymentRow,
    IncidentRow,
    InstructorDetailData,
    Paginated,
    RiskDashboardData,
    RiskOverdueRow,
    RiskRow,
    SecurityAuthLogRow,
    SecuritySessionRow,
    SystemHealth,
    SystemStatistics,
} from "../types/admin";

type Query = Record<string, string | number | boolean | undefined>;

function queryString(query: Query = {}): string {
    const params = new URLSearchParams();
    Object.entries(query).forEach(([key, value]) => {
        if (value !== undefined && value !== "") params.set(key, String(value));
    });
    return params.size ? `?${params.toString()}` : "";
}

async function getJson<T extends object>(path: string, query?: Query): Promise<T> {
    const token = authStorage.getToken();
    const response = await fetch(`${env.apiUrl}${path}${queryString(query)}`, {
        headers: { Accept: "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    });
    const payload = await response.json().catch(() => null) as T | { message?: string } | null;
    if (!response.ok) throw new ApiError(payload && "message" in payload && payload.message ? payload.message : "Unable to load administration data.", response.status);
    return payload as T;
}

async function paginated<T>(path: string, query?: Query): Promise<Paginated<T>> {
    return getJson<Paginated<T>>(path, query);
}

export const adminApi = {
    dashboard: () => api<AdminDashboard>("/v1/admin/dashboard"),
    users: (query?: Query) => paginated<AdminUser>("/v1/admin/users", query),
    courses: (query?: Query) => paginated<AdminCourse>("/v1/admin/courses", query),
    enrollments: (query?: Query) => paginated<AdminEnrollment>("/v1/admin/enrollments", query),
    activity: (query?: Query) => paginated<AdminActivity>("/v1/admin/activity", query),
    broadcasts: (query?: Query) => paginated<AdminBroadcast>("/v1/admin/notifications/broadcasts", query),
    analytics: (kind: "users" | "courses" | "enrollments" | "learning", query?: Query) => api<AnalyticsResponse>(`/v1/admin/analytics/${kind}${queryString(query)}`),
    crmStats: (range: CrmRange) => api<CrmStats>(`/v1/admin/crm/stats${queryString({ range })}`),
    systemHealth: () => api<SystemHealth>("/v1/admin/system/health"),
    systemStatistics: () => api<SystemStatistics>("/v1/admin/system/statistics"),
    auditSummary: () => api<AuditSummary>("/v1/admin/system/audit-log"),
    suspendUser: (id: string) => api<AdminUser>(`/v1/admin/users/${id}/suspend`, { method: "PATCH" }),
    activateUser: (id: string) => api<AdminUser>(`/v1/admin/users/${id}/activate`, { method: "PATCH" }),
    verifyUser: (id: string) => api<AdminUser>(`/v1/admin/users/${id}/verify`, { method: "PATCH" }),
    unverifyUser: (id: string) => api<AdminUser>(`/v1/admin/users/${id}/unverify`, { method: "PATCH" }),
    setUserStatus: (id: string, status: string) => api<AdminUser>(`/v1/admin/users/${id}/status`, { method: "PATCH", body: { status } }),
    setRole: (id: string, role: string) => api<AdminUser>(`/v1/admin/users/${id}/role`, { method: "PATCH", body: { role } }),
    courseAction: (id: string, action: "approve" | "publish" | "archive" | "restore") => api<AdminCourse>(`/v1/admin/courses/${id}/${action}`, { method: "PATCH" }),
    rejectCourse: (id: string, reason: string) => api<AdminCourse>(`/v1/admin/courses/${id}/reject`, { method: "PATCH", body: { reason } }),
    broadcast: (payload: { audience: string; recipient_ids?: string[]; type?: string; title: string; message: string; action_url?: string; replies_enabled?: boolean; quick_replies?: string[] }) => api<AdminBroadcast>("/v1/admin/notifications/broadcast", { method: "POST", body: payload }),
    diagnosticAnalytics: () => api<AdminDiagnosticAnalytics>("/v1/admin/diagnostics/analytics"),
    simulatorAnalytics: () => api<AdminSimulatorAnalytics>("/v1/admin/simulator/analytics"),
    simulatorSessions: (query?: Query) => getJson<AdminSimulatorSessionsPage>("/v1/admin/simulator/sessions", query),
    diagnostics: (query?: Query) => paginated<AdminDiagnosticRow>("/v1/admin/diagnostics", query),
    diagnosticDetail: (id: string) => api<AdminDiagnosticScenarioDetail>(`/v1/admin/diagnostics/${id}`),
    createDiagnostic: (payload: { course_id: string; title: string }) => api<{ id: string; slug: string; version: number }>("/v1/admin/diagnostics", { method: "POST", body: payload }),
    diagnosticLifecycle: (id: string, action: "publish" | "unpublish" | "archive") => api<unknown>(`/v1/admin/diagnostics/${id}/${action}`, { method: "POST" }),
    forkDiagnosticVersion: (id: string) => api<unknown>(`/v1/admin/diagnostics/${id}/fork`, { method: "POST" }),
    createDiagnosticStep: (scenarioId: string, payload: { title: string; action_type: string }) => api<unknown>(`/v1/admin/diagnostics/${scenarioId}/steps`, { method: "POST", body: payload }),
    updateDiagnosticStep: (stepId: string, payload: { title?: string; action_type?: string; is_required?: boolean; is_terminal?: boolean }) => api<unknown>(`/v1/admin/diagnostic-steps/${stepId}`, { method: "PATCH", body: payload }),
    deleteDiagnosticStep: (stepId: string) => api<unknown>(`/v1/admin/diagnostic-steps/${stepId}`, { method: "DELETE" }),
    createDiagnosticCriterion: (scenarioId: string, payload: { key: string; title: string; points: number; evaluation_type: string; step_id?: string | null; rules?: unknown }) => api<unknown>(`/v1/admin/diagnostics/${scenarioId}/criteria`, { method: "POST", body: payload }),
    updateDiagnosticCriterion: (criterionId: string, payload: Record<string, string | number | boolean | null | undefined>) => api<unknown>(`/v1/admin/diagnostic-criteria/${criterionId}`, { method: "PATCH", body: payload }),
    deleteDiagnosticCriterion: (criterionId: string) => api<unknown>(`/v1/admin/diagnostic-criteria/${criterionId}`, { method: "DELETE" }),
    createDiagnosticHint: (scenarioId: string, payload: { content: string; diagnostic_scenario_step_id?: string | null }) => api<unknown>(`/v1/admin/diagnostics/${scenarioId}/hints`, { method: "POST", body: payload }),
    updateDiagnosticHint: (hintId: string, payload: { title?: string | null; content?: string; level?: number; penalty_points?: number }) => api<unknown>(`/v1/admin/diagnostic-hints/${hintId}`, { method: "PATCH", body: payload }),
    deleteDiagnosticHint: (hintId: string) => api<unknown>(`/v1/admin/diagnostic-hints/${hintId}`, { method: "DELETE" }),
    createDiagnosticAssignment: (scenarioId: string, payload: { course_id: string }) => api<unknown>(`/v1/admin/diagnostics/${scenarioId}/assignments`, { method: "POST", body: payload }),
    deleteDiagnosticAssignment: (assignmentId: string) => api<unknown>(`/v1/admin/diagnostic-assignments/${assignmentId}`, { method: "DELETE" }),
    quizzes: (query?: Query) => paginated<AdminQuiz>("/v1/admin/quizzes", query),
    quizDetail: (id: string) => api<AdminQuizDetail>(`/v1/admin/quizzes/${id}`),
    updateQuiz: (id: string, payload: { title?: string; description?: string | null; status?: string; pass_percentage?: number; max_attempts?: number | null; time_limit?: number | null }) => api<unknown>(`/v1/admin/quizzes/${id}`, { method: "PATCH", body: payload }),
    disableQuiz: (id: string) => api<unknown>(`/v1/admin/quizzes/${id}/disable`, { method: "POST" }),
    deleteQuiz: (id: string) => api<unknown>(`/v1/admin/quizzes/${id}`, { method: "DELETE" }),
    quizAttempts: (id: string, query?: Query) => paginated<AdminQuizAttempt>(`/v1/admin/quizzes/${id}/attempts`, query),
    assessments: (query?: Query) => paginated<AdminAssessment>("/v1/admin/assessments", query),
    assessmentDetail: (id: string) => api<AdminAssessmentDetail>(`/v1/admin/assessments/${id}`),
    updateAssessment: (id: string, payload: { title?: string; description?: string | null; status?: string; minimum_score?: number | null; max_attempts?: number | null; is_required?: boolean }) => api<unknown>(`/v1/admin/assessments/${id}`, { method: "PATCH", body: payload }),
    disableAssessment: (id: string) => api<unknown>(`/v1/admin/assessments/${id}/disable`, { method: "POST" }),
    deleteAssessment: (id: string) => api<unknown>(`/v1/admin/assessments/${id}`, { method: "DELETE" }),
    assessmentAttempts: (id: string, query?: Query) => paginated<AdminAssessmentAttempt>(`/v1/admin/assessments/${id}/attempts`, query),
    commerceOverview: () => api<CommerceOverview>("/v1/admin/commerce/overview"),
    commerceTransactions: (query?: Query) => paginated<CommerceTransactionRow>("/v1/admin/commerce/transactions", query),
    confirmTransaction: (id: string) => api<unknown>(`/v1/admin/commerce/transactions/${id}/confirm`, { method: "POST" }),
    failTransaction: (id: string, reason?: string) => api<unknown>(`/v1/admin/commerce/transactions/${id}/fail`, { method: "POST", body: reason ? { reason } : {} }),
    refundTransaction: (id: string, reason?: string) => api<unknown>(`/v1/admin/commerce/transactions/${id}/refund`, { method: "POST", body: reason ? { reason } : {} }),
    commerceRefunds: () => paginated<CommerceRefundRow>("/v1/admin/commerce/refunds"),
    commerceSubscriptions: (query?: Query) => paginated<CommerceSubscriptionRow>("/v1/admin/commerce/subscriptions", query),
    cancelSubscription: (id: string) => api<unknown>(`/v1/admin/commerce/subscriptions/${id}/cancel`, { method: "POST" }),
    grantSubscription: (userId: string, planId: string) => api<unknown>("/v1/admin/commerce/subscriptions/grant", { method: "POST", body: { user_id: userId, plan_id: planId } }),
    commercePayouts: () => paginated<CommercePayoutRow>("/v1/admin/commerce/payouts"),
    recordPayout: (payload: { instructor_id: string; amount: number; currency?: string; period?: string; note?: string }) => api<unknown>("/v1/admin/commerce/payouts", { method: "POST", body: payload }),
    markPayoutPaid: (id: string) => api<unknown>(`/v1/admin/commerce/payouts/${id}/pay`, { method: "POST" }),
    autoGeneratePayouts: (period?: string) => api<unknown>("/v1/admin/commerce/payouts/auto-generate", { method: "POST", body: period ? { period } : {} }),
    plans: () => api<Array<{ id: string; name: string; price: number; currency: string; interval: string; trial_days: number; active: boolean; subscribers?: number }>>("/v1/admin/plans"),
    createPlan: (payload: Record<string, string | number | boolean | string[] | null>) => api<unknown>("/v1/admin/plans", { method: "POST", body: payload }),
    updatePlan: (id: string, payload: Record<string, string | number | boolean | string[] | null | undefined>) => api<unknown>(`/v1/admin/plans/${id}`, { method: "PATCH", body: payload }),
    deletePlan: (id: string) => api<unknown>(`/v1/admin/plans/${id}`, { method: "DELETE" }),
    commerceOrders: (query?: Query) => paginated<CommerceOrderRow>("/v1/admin/payments/orders", query),
    commerceInvoices: (query?: Query) => paginated<CommerceInvoiceRow>("/v1/admin/payments/invoices", query),
    commerceWebhooks: (query?: Query) => paginated<CommerceWebhookRow>("/v1/admin/payments/webhooks", query),
    replayWebhook: (id: string) => api<unknown>(`/v1/admin/payments/webhooks/${id}/replay`, { method: "POST" }),
    failedPayments: () => paginated<FailedPaymentRow>("/v1/admin/payments/failed"),
    supportTickets: (query?: Query) => paginated<AdminSupportTicket>("/v1/admin/support/tickets", query),
    supportTicketDetail: (id: string) => api<AdminSupportTicketDetail>(`/v1/admin/support/tickets/${id}`),
    supportReply: (id: string, message: string, internal?: boolean) => api<unknown>(`/v1/admin/support/tickets/${id}/replies`, { method: "POST", body: { message, internal: internal ?? false } }),
    supportAssign: (id: string, assigneeId: string) => api<unknown>(`/v1/admin/support/tickets/${id}/assign`, { method: "PATCH", body: { assignee_id: assigneeId } }),
    supportEscalate: (id: string, level: string, note?: string) => api<unknown>(`/v1/admin/support/tickets/${id}/escalate`, { method: "POST", body: note ? { level, note } : { level } }),
    supportResolve: (id: string) => api<unknown>(`/v1/admin/support/tickets/${id}/resolve`, { method: "POST" }),
    supportClose: (id: string) => api<unknown>(`/v1/admin/support/tickets/${id}/close`, { method: "POST" }),
    students: (query?: Query) => paginated<AdminStudent>("/v1/admin/students", query),
    studentJourney: (id: string) => api<AdminStudentJourney>(`/v1/admin/students/${id}`),
    instructors: (query?: Query) => paginated<AdminInstructor>("/v1/admin/instructors", query),
    instructorDetail: (id: string) => api<InstructorDetailData>(`/v1/admin/instructors/${id}`),
    roles: () => api<{ roles: Array<{ name: string; permissions: string[]; users_count: number; protected: boolean }>; catalog: Record<string, string[]> }>("/v1/admin/roles"),
    updateRolePermissions: (role: string, permissions: string[]) => api<{ name: string; permissions: string[] }>(`/v1/admin/roles/${role}/permissions`, { method: "PUT", body: { permissions } }),
    securityOverview: () => api<Record<string, number>>("/v1/admin/security/overview"),
    securityAuthLogs: (query?: Query) => paginated<SecurityAuthLogRow>("/v1/admin/security/auth-logs", query),
    securitySessions: (query?: Query) => paginated<SecuritySessionRow>("/v1/admin/security/sessions", query),
    securityAlerts: () => api<Array<{ title: string; detail: string; severity: string }>>("/v1/admin/security/alerts"),
    revokeSecuritySession: (id: string) => api<unknown>(`/v1/admin/security/sessions/${id}/revoke`, { method: "POST" }),
    riskDashboard: () => api<RiskDashboardData>("/v1/admin/risks-dashboard"),
    risks: (query?: Query) => paginated<RiskRow>("/v1/admin/risks", query),
    incidents: (query?: Query) => paginated<IncidentRow>("/v1/admin/security-incidents", query),
    riskOverdue: () => api<RiskOverdueRow[]>("/v1/admin/risk-reports/overdue"),
    riskFailedControls: () => api<FailedControlRow[]>("/v1/admin/risk-reports/failed-controls"),
    createRisk: (payload: { title: string; probability: number; impact: number }) => api<unknown>("/v1/admin/risks", { method: "POST", body: payload }),
};
