<?php

namespace App\Domains\Security\Enums;

enum SecurityEventType: string
{
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case MFA_ENABLED = 'MFA_ENABLED';
    case MFA_DISABLED = 'MFA_DISABLED';
    case SESSION_CREATED = 'SESSION_CREATED';
    case SESSION_REVOKED = 'SESSION_REVOKED';
    case PERMISSION_DENIED = 'PERMISSION_DENIED';
    case ACCOUNT_LOCKED = 'ACCOUNT_LOCKED';
    case SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN';
    case API_RATE_LIMITED = 'API_RATE_LIMITED';
    case FILE_UPLOAD_REJECTED = 'FILE_UPLOAD_REJECTED';
    case PAYMENT_WEBHOOK_REJECTED = 'PAYMENT_WEBHOOK_REJECTED';
    case ADMIN_ROLE_GRANTED = 'ADMIN_ROLE_GRANTED';
    case ADMIN_ROLE_REVOKED = 'ADMIN_ROLE_REVOKED';
    case SENSITIVE_OPERATION = 'SENSITIVE_OPERATION';
}
