import { useDeferredValue, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, Filter, Search, ShieldCheck } from "lucide-react";

import { useTranslation } from "react-i18next";

import { adminApi } from "../api/adminApi";
import { AdminHeading, AdminPanel, ErrorAdminPage, LoadingAdminPage, PageControls } from "../components/AdminUi";

export function AdminActivityPage() {
    const { t, i18n } = useTranslation(); const isRTL = i18n.language === "ar";
    const [search, setSearch] = useState(""); const [target, setTarget] = useState(""); const [page, setPage] = useState(1); const deferred = useDeferredValue(search);
    const activity = useQuery({ queryKey: ["admin", "activity", deferred, target, page], queryFn: () => adminApi.activity({ search: deferred, target_type: target, page, per_page: 15 }) });
    if (activity.isLoading) return <LoadingAdminPage />; if (activity.isError || !activity.data) return <ErrorAdminPage onRetry={() => void activity.refetch()} />; const data = activity.data;
    return <div className="mx-auto max-w-7xl space-y-6"><AdminHeading eyebrow={t("admin.activity.eyebrow")} title={t("admin.activity.title")} description={t("admin.activity.description")} /><div className="grid gap-4 sm:grid-cols-3"><Signal label={t("admin.activity.signals.entries")} value={data.meta.total} icon={Activity} /><Signal label={t("admin.activity.signals.immutable")} value={t("admin.activity.signals.immutableValue")} icon={ShieldCheck} /><Signal label={t("admin.activity.signals.scope")} value={t("admin.activity.signals.scopeValue")} icon={Filter} /></div><AdminPanel><div className="flex flex-wrap gap-3"><label className="relative min-w-[220px] flex-1"><Search className={`pointer-events-none absolute top-1/2 h-4 w-4 -translate-y-1/2 text-[#3A3A3A]/38 ${isRTL ? "right-3" : "left-3"}`} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder={t("admin.activity.searchPh")} className={`h-11 w-full rounded-xl border border-[#3A3A3A]/10 bg-[#FCFCFC] text-sm outline-none focus:border-[#F47822] ${isRTL ? "pl-3 pr-10" : "pl-10 pr-3"}`} /></label><select value={target} onChange={(event) => { setTarget(event.target.value); setPage(1); }} className="h-11 rounded-xl border border-[#3A3A3A]/10 bg-white px-3 text-xs font-semibold outline-none focus:border-[#F47822]"><option value="">{t("admin.activity.filters.all")}</option><option value="course">{t("admin.activity.filters.courses")}</option><option value="enrollment">{t("admin.activity.filters.enrollments")}</option><option value="user">{t("admin.activity.filters.users")}</option></select></div><div className="mt-6 divide-y divide-[#3A3A3A]/7">{data.data.map((item) => <article key={item.id} className="flex flex-col gap-3 py-4 first:pt-0 md:flex-row md:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#F47822]/10 text-[#F47822]"><Activity className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{headline(item.event)}</p><span className="rounded-full bg-[#3A3A3A]/6 px-2 py-1 text-[10px] font-bold text-[#3A3A3A]/50">{item.target.type} · {item.target.id.slice(0, 8)}</span></div><p className="mt-1 text-xs text-[#3A3A3A]/48">{item.actor ? `${item.actor.name} (${item.actor.email})` : t("admin.activity.systemActor")}{item.metadata?.reason ? ` · ${String(item.metadata.reason)}` : ""}</p></div><p className="shrink-0 text-[11px] text-[#3A3A3A]/42">{item.occurred_at ? formatTime(item.occurred_at, i18n.language) : "—"}</p></article>)}</div><div className="mt-5"><PageControls page={data.meta.current_page} lastPage={data.meta.last_page} onPage={setPage} /></div></AdminPanel></div>;
}
function Signal({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Activity }) { return <div className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-4"><Icon className="h-4 w-4 text-[#F47822]" /><p className="mt-4 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#3A3A3A]/47">{label}</p></div>; }
function headline(value: string) { return value.split(".").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" · "); }
function formatTime(value: string, locale: string) { return new Intl.DateTimeFormat(locale, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
