import { CheckCircle2, ClipboardCheck, Loader2, PlayCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { env } from "@/config/env";
import { authStorage } from "@/lib/storage/auth-storage";
import { useNavigate } from "react-router-dom";

type Quiz = { id: string; title: string; questions_count: number; pass_percentage: number };
type Attempt = { id: string; quiz_id: string; status: string; percentage: number | null; passed: boolean | null; quiz: { title: string; pass_percentage: number; questions: { id: string; question: string; options: { id: string; option: string; is_correct: boolean | null }[] }[] } };
const headers = () => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${authStorage.getToken() ?? ""}` });

export function LessonQuizCheckpoints({ courseId }: { courseId: string }) {
    const navigate = useNavigate();
    const [quizzes, setQuizzes] = useState<Quiz[]>([]); const [attempt, setAttempt] = useState<Attempt | null>(null); const [answers, setAnswers] = useState<Record<string, string[]>>({}); const [busy, setBusy] = useState(false);
    useEffect(() => { void fetch(`${env.apiUrl}/v1/courses/${courseId}/quizzes`, { headers: headers() }).then(async response => response.ok ? response.json() as Promise<{ data: Quiz[] }> : null).then(payload => setQuizzes(payload?.data ?? [])).catch(() => setQuizzes([])); }, [courseId]);
    const start = async (quiz: Quiz) => { setBusy(true); try { const response = await fetch(`${env.apiUrl}/v1/quizzes/${quiz.id}/attempts`, { method: "POST", headers: headers(), body: "{}" }); const payload = await response.json() as { data: Attempt }; if (!response.ok) throw new Error(); setAttempt(payload.data); } finally { setBusy(false); } };
    const submit = async () => { if (!attempt) return; setBusy(true); try { const response = await fetch(`${env.apiUrl}/v1/quizzes/${attempt.quiz_id}/attempts/${attempt.id}/submit`, { method: "POST", headers: headers(), body: JSON.stringify({ answers }) }); const payload = await response.json() as { data: Attempt }; if (!response.ok) throw new Error(); setAttempt(payload.data); } finally { setBusy(false); } };
    if (attempt) return <div className="border-t border-border bg-[#F47822]/[0.03] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-bold text-foreground">{attempt.quiz.title}</p><button onClick={() => setAttempt(null)} className="text-[10px] text-muted-foreground">Close</button></div>{attempt.status === "submitted" ? <div className="mt-3 rounded-xl bg-white p-3 text-center"><CheckCircle2 className={attempt.passed ? "mx-auto h-5 w-5 text-emerald-600" : "mx-auto h-5 w-5 text-red-500"}/><p className="mt-1 text-xs font-bold">{attempt.percentage}% · {attempt.passed ? "Checkpoint passed" : "Try again"}</p></div> : <><div className="mt-3 space-y-3">{attempt.quiz.questions.map(question => <div key={question.id} className="rounded-xl bg-white p-3"><p className="text-[11px] font-semibold text-foreground">{question.question}</p><div className="mt-2 space-y-1">{question.options.map(option => <label key={option.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-1 py-1 text-[10px] text-muted-foreground hover:bg-[#F47822]/5"><input type="radio" name={question.id} checked={answers[question.id]?.[0] === option.id} onChange={() => setAnswers(value => ({ ...value, [question.id]: [option.id] }))} />{option.option}</label>)}</div></div>)}</div><button disabled={busy} onClick={() => void submit()} className="mt-3 flex w-full items-center justify-center rounded-lg bg-[#F47822] px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-60">{busy ? "Submitting…" : "Submit checkpoint"}</button></>}</div>;
    if (quizzes.length === 0) return null;
    return <div className="border-t border-border bg-[#F7F7F7] p-3"><p className="mb-2 text-[9px] font-bold uppercase tracking-[0.12em] text-[#F47822]">Course checkpoints</p>{quizzes.map(quiz => <button key={quiz.id} disabled={busy} onClick={() => navigate(`/courses/${courseId}/quizzes/${quiz.id}`)} className="group flex w-full items-center gap-2 rounded-xl bg-white p-2.5 text-left transition hover:bg-[#F47822]/5"><div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#F47822]/10 text-[#F47822]"><ClipboardCheck className="h-3.5 w-3.5"/></div><span className="min-w-0 flex-1 truncate text-[10px] font-semibold text-foreground">{quiz.title}</span><PlayCircle className="h-3.5 w-3.5 text-[#F47822]"/></button>)}</div>;
}
