import { ArrowRight, Award, CheckCircle2, ClipboardCheck, Clock3, LockKeyhole, PlayCircle, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { getAssessments, type Assessment } from "../api/assessments.api";

export function AssessmentsPage() {
    const { t } = useTranslation();
    const [items, setItems] = useState<Assessment[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [selected, setSelected] = useState<Assessment | null>(null);

    useEffect(() => {
        void getAssessments().then(setItems).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : t("assessments.loadFail"))).finally(() => setLoading(false));
    }, []);

    if (loading) return <main className="min-h-full bg-background p-8 text-sm text-muted-foreground">{t("assessments.loading")}</main>;
    if (error) return <main className="min-h-full bg-background p-8"><div className="rounded-2xl bg-red-50 dark:bg-red-500/10 p-5 text-red-700 dark:text-red-400">{error}</div></main>;

    return <main className="min-h-full bg-background"><div className="mx-auto max-w-[1440px] px-5 py-6 sm:px-8 sm:py-8 lg:px-10">
        <section className="rounded-3xl bg-[#3A3A3A] p-7 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#F47822]">{t("assessments.hero.eyebrow")}</p><div className="mt-2 flex items-end justify-between gap-5"><div><h1 className="text-2xl font-bold">{t("assessments.hero.title")}</h1><p className="mt-1 text-sm text-white/60">{t("assessments.hero.description")}</p></div><div className="flex items-center gap-3 rounded-2xl bg-white/10 px-4 py-3"><Award className="h-5 w-5 text-[#F47822]"/><b>{items.filter(item => item.eligibility.eligible).length}</b></div></div></section>
        <section className="mt-6 grid gap-5 lg:grid-cols-2">{items.map(item => <article key={item.id} className="rounded-3xl border border-[#3A3A3A]/10 dark:border-white/10 bg-white dark:bg-[#1b1b20] p-6 shadow-sm"><div className="flex justify-between"><ClipboardCheck className="h-5 w-5 text-[#F47822]"/>{item.eligibility.eligible ? <CheckCircle2 className="h-5 w-5 text-emerald-600 dark:text-emerald-400"/> : <LockKeyhole className="h-5 w-5 text-[#3A3A3A]/35 dark:text-white/35"/>}</div><p className="mt-5 text-[10px] font-bold uppercase tracking-[.15em] text-[#F47822]">{item.course_title}</p><h2 className="mt-2 text-xl font-bold">{item.title}</h2><p className="mt-2 text-sm text-muted-foreground">{item.description}</p><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><Requirement label={t("assessments.reqLessons")} value={`${item.eligibility.lessons.completed}/${item.eligibility.lessons.required}`}/><Requirement label={t("assessments.reqQuizzes")} value={`${item.eligibility.quizzes.completed}/${item.eligibility.quizzes.required}`}/><Requirement label={t("assessments.reqScenarios")} value={`${item.eligibility.scenarios.completed}/${item.eligibility.scenarios.required}`}/></div>{item.eligibility.eligible ? <button onClick={() => setSelected(item)} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#F47822] px-4 py-3 text-sm font-semibold text-white hover:bg-[#df6817]"><PlayCircle className="h-4 w-4"/>{t("assessments.startBtn")}</button> : <button disabled className="mt-5 w-full rounded-xl bg-[#3A3A3A]/10 dark:bg-white/10 px-4 py-3 text-sm text-[#3A3A3A]/40 dark:text-white/40">{t("assessments.lockedBtn")}</button>}</article>)}</section>
    </div>{selected && <ExamInstructions assessment={selected} onClose={() => setSelected(null)} />}</main>;
}

function ExamInstructions({ assessment, onClose }: { assessment: Assessment; onClose: () => void }) { const { t } = useTranslation(); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#3A3A3A]/60 dark:bg-white/60 p-5 backdrop-blur-sm"><div role="dialog" aria-modal="true" aria-labelledby="exam-instructions-title" className="w-full max-w-xl overflow-hidden rounded-3xl bg-white dark:bg-[#1b1b20] shadow-2xl"><header className="relative overflow-hidden bg-[#3A3A3A] px-6 py-7 text-white sm:px-7"><div className="absolute -right-10 -top-14 h-40 w-40 rounded-full bg-[#F47822]/20 blur-3xl"/><button type="button" onClick={onClose} className="absolute end-4 top-4 rounded-lg p-1.5 text-white/55 transition hover:bg-white/10 hover:text-white" aria-label={t("assessments.closeAria")}><X className="h-5 w-5"/></button><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#F47822]">{t("assessments.examTag")}</p><h2 id="exam-instructions-title" className="mt-2 max-w-md text-2xl font-bold tracking-tight">{t("assessments.readyTitle")}</h2><p className="mt-2 text-sm leading-6 text-white/60">{assessment.title}</p></div></header><div className="p-6 sm:p-7"><div className="grid grid-cols-3 gap-3"><Info icon={Clock3} label={t("assessments.duration")} value={t("assessments.durationValue")}/><Info icon={ClipboardCheck} label={t("assessments.questions")} value={`${assessment.questions_count}`}/><Info icon={Award} label={t("assessments.attempts")} value={assessment.max_attempts ? `${assessment.max_attempts}` : t("assessments.openAttempts")}/></div><div className="mt-5 rounded-2xl border border-[#F47822]/15 bg-[#F47822]/5 p-4"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#F47822]/10"><ShieldCheck className="h-4 w-4 text-[#F47822]"/></div><div><h3 className="text-sm font-bold text-[#3A3A3A] dark:text-[#ececef]">{t("assessments.focusedTitle")}</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-[#3A3A3A]/60 dark:text-white/60"><li>• {t("assessments.ruleTimer")}</li><li>• {t("assessments.ruleTabs")}</li><li>• {t("assessments.ruleSubmit")}</li></ul></div></div></div><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-xl border border-[#3A3A3A]/10 dark:border-white/10 px-4 py-3 text-sm font-semibold text-[#3A3A3A]/65 dark:text-white/65 transition hover:bg-[#F7F7F7] dark:hover:bg-[#101013]">{t("assessments.notNow")}</button><Link to={`/assessments/${assessment.id}/exam`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#F47822] px-5 py-3 text-sm font-bold text-white shadow-[0_8px_20px_rgba(244,120,34,.2)] transition hover:bg-[#df6817]">{t("assessments.beginBtn")} <ArrowRight className="h-4 w-4 rtl:-scale-x-100"/></Link></div></div></div></div>; }
function Info({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="rounded-xl bg-[#F7F7F7] dark:bg-[#101013] p-3"><Icon className="h-4 w-4 text-[#F47822]"/><p className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-[#3A3A3A]/40 dark:text-white/40">{label}</p><p className="mt-1 text-xs font-bold text-[#3A3A3A] dark:text-[#ececef]">{value}</p></div>; }

function Requirement({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#F7F7F7] dark:bg-[#101013] p-3"><span className="text-[#3A3A3A]/50 dark:text-white/50">{label}</span><b className="mt-1 block">{value}</b></div>; }
