import {
    Activity,
    ArrowLeft,
    BarChart3,
    BookOpen,
    ClipboardCheck,
    Clock3,
    TrendingDown,
    Users,
} from "lucide-react";
import {
    Link,
    useParams,
} from "react-router-dom";

import {
    useInstructorCourseAnalytics,
} from "../hooks/useInstructorCourseAnalytics";

export function InstructorCourseAnalyticsPage() {
    const { courseId } = useParams();
    const analytics = useInstructorCourseAnalytics(courseId ?? "");

    if (analytics.isLoading) return <AnalyticsSkeleton />;
    if (analytics.isError || !analytics.data) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6"><h1 className="font-semibold text-red-900">Analytics unavailable</h1><p className="mt-2 text-sm text-red-700">You can only view analytics for courses you own.</p></div>;
    const data = analytics.data;
    const maxEnrollments = Math.max(...data.enrollment.last_7_days.map((item) => item.enrollments), 1);

    return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link to={`/instructor/courses/${courseId}`} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#3A3A3A]/50 hover:text-[#F47822]"><ArrowLeft className="h-3.5 w-3.5" /> Course editor</Link><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-[#F47822]">Learning intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#3A3A3A]">{data.course.title}</h1><p className="mt-2 text-sm leading-6 text-[#3A3A3A]/50">Understand where learners are progressing, engaging, and need extra support.</p></div><span className="rounded-xl bg-[#3A3A3A] px-4 py-3 text-xs font-semibold text-white">{data.students.enrolled} enrolled</span></header>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Enrolled students" value={data.students.enrolled} detail={`+${data.enrollment.new_this_month} this month`} /><Metric icon={Activity} label="Average progress" value={`${data.students.average_progress}%`} detail={`${data.students.in_progress} in progress`} /><Metric icon={ClipboardCheck} label="Completion rate" value={`${data.students.completion_rate}%`} detail={`${data.students.completed} completed`} /><Metric icon={Clock3} label="Learning time" value={`${data.learning.total_time_hours}h`} detail={`${data.lessons.completed} lessons completed`} /></div>
        <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={BarChart3} title="Enrollment activity" subtitle="New learner enrollments over the last seven days." /><div className="mt-6 flex h-36 items-end justify-between gap-2">{data.enrollment.last_7_days.map((item) => <div key={item.date} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-28 w-full items-end rounded-t-lg bg-[#F47822]/8"><div className="w-full rounded-t-lg bg-[#F47822] transition-all" style={{ height: `${Math.max((item.enrollments / maxEnrollments) * 100, item.enrollments ? 10 : 2)}%` }} /></div><span className="text-[10px] text-[#3A3A3A]/40">{new Intl.DateTimeFormat(undefined, { weekday: "narrow" }).format(new Date(item.date))}</span></div>)}</div></section><section className="rounded-2xl border border-[#3A3A3A]/8 bg-[#3A3A3A] p-5 text-white shadow-[0_8px_30px_rgba(58,58,58,.1)]"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#F9A16C]">Engagement snapshot</p><div className="mt-5 space-y-5"><Engagement label="Active in last 7 days" value={data.engagement.active_last_7_days} /><Engagement label="Active in last 30 days" value={data.engagement.active_last_30_days} /><Engagement label="Inactive for 14+ days" value={data.engagement.inactive_over_14_days} warning /></div></section></div>
        <div className="grid gap-6 lg:grid-cols-2"><PerformanceList title="Section performance" subtitle="Average lesson progress per curriculum section." items={data.sections.map((item) => ({ id: item.id, title: `${item.position}. ${item.title}`, value: item.average_progress, detail: `${item.lessons_count} lessons · ${item.completed_lessons} completions` }))} empty="Build your curriculum to view section performance." /><PerformanceList title="Lesson performance" subtitle="Individual lessons that show where learners continue or stall." items={data.lesson_performance.map((item) => ({ id: item.id, title: item.title, value: item.average_progress, detail: `${item.completed_students} completed · ${item.started_students} started` }))} empty="Lesson performance appears after learners begin." /></div>
        <section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={ClipboardCheck} title="Quiz performance" subtitle="Attempt volume, average score, and pass rate for every quiz checkpoint." />{data.quizzes.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left"><thead className="border-b border-[#3A3A3A]/7 text-[10px] font-bold uppercase tracking-[.12em] text-[#3A3A3A]/35"><tr><th className="pb-3">Quiz</th><th className="pb-3">Attempts</th><th className="pb-3">Students</th><th className="pb-3">Average score</th><th className="pb-3">Pass rate</th></tr></thead><tbody className="divide-y divide-[#3A3A3A]/7">{data.quizzes.map((quiz) => <tr key={quiz.id}><td className="py-4 text-sm font-semibold text-[#3A3A3A]">{quiz.title}</td><td className="py-4 text-sm text-[#3A3A3A]/60">{quiz.attempts}</td><td className="py-4 text-sm text-[#3A3A3A]/60">{quiz.unique_students}</td><td className="py-4 text-sm font-semibold text-[#3A3A3A]">{quiz.average_score}%</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${quiz.pass_rate >= 70 ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{quiz.pass_rate}%</span></td></tr>)}</tbody></table></div> : <Empty text="No quiz performance yet. Create a checkpoint in the curriculum builder." />}</section>
        <section className="rounded-2xl border border-[#F47822]/18 bg-[#F47822]/5 p-5"><SectionHeading icon={TrendingDown} title="Needs attention" subtitle="Learners enrolled for at least 30 days with under 30% progress and no activity for 14 days." />{data.engagement.at_risk_students.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.engagement.at_risk_students.map((student) => <Link key={student.student_id} to={`/instructor/students/${student.student_id}`} className="flex items-center gap-3 rounded-xl border border-[#F47822]/15 bg-white p-3.5 transition hover:border-[#F47822]/40"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#F47822]/10 text-xs font-bold text-[#F47822]">{student.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#3A3A3A]">{student.name}</p><p className="mt-1 truncate text-xs text-[#3A3A3A]/45">{student.email}</p></div><span className="text-sm font-bold text-[#F47822]">{student.progress}%</span></Link>)}</div> : <Empty text="No learners currently match the at-risk criteria." />}</section>
    </div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Users; label: string; value: string | number; detail: string }) { return <div className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[#3A3A3A]/45">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-[#3A3A3A]">{value}</p><p className="mt-2 text-[11px] text-[#3A3A3A]/45">{detail}</p></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F47822]/10 text-[#F47822]"><Icon className="h-5 w-5" /></div></div></div>; }
function SectionHeading({ icon: Icon, title, subtitle }: { icon: typeof Users; title: string; subtitle: string }) { return <div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F47822]/10 text-[#F47822]"><Icon className="h-4 w-4" /></div><div><h2 className="font-semibold text-[#3A3A3A]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#3A3A3A]/45">{subtitle}</p></div></div>; }
function Engagement({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="text-sm text-white/65">{label}</span><span className={`rounded-full px-3 py-1 text-sm font-bold ${warning ? "bg-[#F47822] text-white" : "bg-white/10 text-white"}`}>{value}</span></div>; }
function PerformanceList({ title, subtitle, items, empty }: { title: string; subtitle: string; items: Array<{ id: string; title: string; value: number; detail: string }>; empty: string }) { return <section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={BookOpen} title={title} subtitle={subtitle} />{items.length ? <div className="mt-5 space-y-4">{items.map((item) => <div key={item.id}><div className="flex items-end justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#3A3A3A]">{item.title}</p><p className="mt-1 text-[11px] text-[#3A3A3A]/45">{item.detail}</p></div><span className="text-sm font-bold text-[#3A3A3A]">{item.value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#3A3A3A]/7"><div className="h-full rounded-full bg-[#F47822]" style={{ width: `${item.value}%` }} /></div></div>)}</div> : <div className="mt-5"><Empty text={empty} /></div>}</section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-[#FCFCFC] px-4 py-6 text-center text-xs leading-5 text-[#3A3A3A]/45">{text}</p>; }
function AnalyticsSkeleton() { return <div className="mx-auto max-w-6xl space-y-5"><div className="h-32 animate-pulse rounded-2xl bg-black/5" /><div className="grid gap-4 sm:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-black/5" />)}</div><div className="h-80 animate-pulse rounded-2xl bg-black/5" /></div>; }
