import {
    Activity,
    ArrowLeft,
    BarChart3,
    BookOpen,
    ClipboardCheck,
    Clock3,
    TrendingDown,
    Users,
} from "lucide-react";
import {
    Link,
    useParams,
} from "react-router-dom";
import { useTranslation } from "react-i18next";

import {
    useInstructorCourseAnalytics,
} from "../hooks/useInstructorCourseAnalytics";

export function InstructorCourseAnalyticsPage() {
    const { t, i18n } = useTranslation();
    const locale = i18n.language;
    const { courseId } = useParams();
    const analytics = useInstructorCourseAnalytics(courseId ?? "");

    if (analytics.isLoading) return <AnalyticsSkeleton />;
    if (analytics.isError || !analytics.data) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6"><h1 className="font-semibold text-red-900">{t("instructor.analytics.errorTitle")}</h1><p className="mt-2 text-sm text-red-700">{t("instructor.analytics.errorDesc")}</p></div>;
    const data = analytics.data;
    const maxEnrollments = Math.max(...data.enrollment.last_7_days.map((item) => item.enrollments), 1);

    return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link to={`/instructor/courses/${courseId}`} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#3A3A3A]/50 hover:text-[#F47822]"><ArrowLeft className="h-3.5 w-3.5 rtl:-scale-x-100" /> {t("instructor.analytics.back")}</Link><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-[#F47822]">{t("instructor.analytics.eyebrow")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#3A3A3A]">{data.course.title}</h1><p className="mt-2 text-sm leading-6 text-[#3A3A3A]/50">{t("instructor.analytics.description")}</p></div><span className="rounded-xl bg-[#3A3A3A] px-4 py-3 text-xs font-semibold text-white">{t("instructor.analytics.enrolledBadge", { count: data.students.enrolled })}</span></header>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label={t("instructor.analytics.metrics.enrolled")} value={data.students.enrolled} detail={t("instructor.analytics.metrics.thisMonth", { count: data.enrollment.new_this_month })} /><Metric icon={Activity} label={t("instructor.analytics.metrics.avgProgress")} value={`${data.students.average_progress}%`} detail={t("instructor.analytics.metrics.inProgress", { count: data.students.in_progress })} /><Metric icon={ClipboardCheck} label={t("instructor.analytics.metrics.completion")} value={`${data.students.completion_rate}%`} detail={t("instructor.analytics.metrics.completed", { count: data.students.completed })} /><Metric icon={Clock3} label={t("instructor.analytics.metrics.time")} value={`${data.learning.total_time_hours}h`} detail={t("instructor.analytics.metrics.lessonsDone", { count: data.lessons.completed })} /></div>
        <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={BarChart3} title={t("instructor.analytics.enrollmentTitle")} subtitle={t("instructor.analytics.enrollmentSub")} /><div className="mt-6 flex h-36 items-end justify-between gap-2">{data.enrollment.last_7_days.map((item) => <div key={item.date} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-28 w-full items-end rounded-t-lg bg-[#F47822]/8"><div className="w-full rounded-t-lg bg-[#F47822] transition-all" style={{ height: `${Math.max((item.enrollments / maxEnrollments) * 100, item.enrollments ? 10 : 2)}%` }} /></div><span className="text-[10px] text-[#3A3A3A]/40">{new Intl.DateTimeFormat(locale, { weekday: "narrow" }).format(new Date(item.date))}</span></div>)}</div></section><section className="rounded-2xl border border-[#3A3A3A]/8 bg-[#3A3A3A] p-5 text-white shadow-[0_8px_30px_rgba(58,58,58,.1)]"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#F9A16C]">{t("instructor.analytics.engagementTitle")}</p><div className="mt-5 space-y-5"><Engagement label={t("instructor.analytics.active7")} value={data.engagement.active_last_7_days} /><Engagement label={t("instructor.analytics.active30")} value={data.engagement.active_last_30_days} /><Engagement label={t("instructor.analytics.inactive")} value={data.engagement.inactive_over_14_days} warning /></div></section></div>
        <div className="grid gap-6 lg:grid-cols-2"><PerformanceList title={t("instructor.analytics.sectionTitle")} subtitle={t("instructor.analytics.sectionSub")} items={data.sections.map((item) => ({ id: item.id, title: `${item.position}. ${item.title}`, value: item.average_progress, detail: t("instructor.analytics.sectionDetail", { lessons: item.lessons_count, done: item.completed_lessons }) }))} empty={t("instructor.analytics.sectionEmpty")} /><PerformanceList title={t("instructor.analytics.lessonTitle")} subtitle={t("instructor.analytics.lessonSub")} items={data.lesson_performance.map((item) => ({ id: item.id, title: item.title, value: item.average_progress, detail: t("instructor.analytics.lessonDetail", { done: item.completed_students, started: item.started_students }) }))} empty={t("instructor.analytics.lessonEmpty")} /></div>
        <section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={ClipboardCheck} title={t("instructor.analytics.quizTitle")} subtitle={t("instructor.analytics.quizSub")} />{data.quizzes.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left rtl:text-right"><thead className="border-b border-[#3A3A3A]/7 text-[10px] font-bold uppercase tracking-[.12em] text-[#3A3A3A]/35"><tr><th className="pb-3">{t("instructor.analytics.colQuiz")}</th><th className="pb-3">{t("instructor.analytics.colAttempts")}</th><th className="pb-3">{t("instructor.analytics.colStudents")}</th><th className="pb-3">{t("instructor.analytics.colAvg")}</th><th className="pb-3">{t("instructor.analytics.colPass")}</th></tr></thead><tbody className="divide-y divide-[#3A3A3A]/7">{data.quizzes.map((quiz) => <tr key={quiz.id}><td className="py-4 text-sm font-semibold text-[#3A3A3A]">{quiz.title}</td><td className="py-4 text-sm text-[#3A3A3A]/60">{quiz.attempts}</td><td className="py-4 text-sm text-[#3A3A3A]/60">{quiz.unique_students}</td><td className="py-4 text-sm font-semibold text-[#3A3A3A]">{quiz.average_score}%</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${quiz.pass_rate >= 70 ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{quiz.pass_rate}%</span></td></tr>)}</tbody></table></div> : <Empty text={t("instructor.analytics.quizEmpty")} />}</section>
        <section className="rounded-2xl border border-[#F47822]/18 bg-[#F47822]/5 p-5"><SectionHeading icon={TrendingDown} title={t("instructor.analytics.attentionTitle")} subtitle={t("instructor.analytics.attentionSub")} />{data.engagement.at_risk_students.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.engagement.at_risk_students.map((student) => <Link key={student.student_id} to={`/instructor/students/${student.student_id}`} className="flex items-center gap-3 rounded-xl border border-[#F47822]/15 bg-white p-3.5 transition hover:border-[#F47822]/40"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#F47822]/10 text-xs font-bold text-[#F47822]">{student.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#3A3A3A]">{student.name}</p><p className="mt-1 truncate text-xs text-[#3A3A3A]/45">{student.email}</p></div><span className="shrink-0 text-sm font-bold text-[#F47822]">{student.progress}%</span></Link>)}</div> : <Empty text={t("instructor.analytics.attentionEmpty")} />}</section>
    </div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Users; label: string; value: string | number; detail: string }) { return <div className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-[#3A3A3A]/45">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-[#3A3A3A]">{value}</p><p className="mt-2 text-[11px] text-[#3A3A3A]/45">{detail}</p></div><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F47822]/10 text-[#F47822]"><Icon className="h-5 w-5" /></div></div></div>; }
function SectionHeading({ icon: Icon, title, subtitle }: { icon: typeof Users; title: string; subtitle: string }) { return <div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#F47822]/10 text-[#F47822]"><Icon className="h-4 w-4" /></div><div><h2 className="font-semibold text-[#3A3A3A]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#3A3A3A]/45">{subtitle}</p></div></div>; }
function Engagement({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="text-sm text-white/65">{label}</span><span className={`shrink-0 rounded-full px-3 py-1 text-sm font-bold ${warning ? "bg-[#F47822] text-white" : "bg-white/10 text-white"}`}>{value}</span></div>; }
function PerformanceList({ title, subtitle, items, empty }: { title: string; subtitle: string; items: Array<{ id: string; title: string; value: number; detail: string }>; empty: string }) { return <section className="rounded-2xl border border-[#3A3A3A]/8 bg-white p-5 shadow-[0_8px_30px_rgba(58,58,58,.04)]"><SectionHeading icon={BookOpen} title={title} subtitle={subtitle} />{items.length ? <div className="mt-5 space-y-4">{items.map((item) => <div key={item.id}><div className="flex items-end justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#3A3A3A]">{item.title}</p><p className="mt-1 text-[11px] text-[#3A3A3A]/45">{item.detail}</p></div><span className="shrink-0 text-sm font-bold text-[#3A3A3A]">{item.value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#3A3A3A]/7"><div className="h-full rounded-full bg-[#F47822]" style={{ width: `${item.value}%` }} /></div></div>)}</div> : <div className="mt-5"><Empty text={empty} /></div>}</section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-[#FCFCFC] px-4 py-6 text-center text-xs leading-5 text-[#3A3A3A]/45">{text}</p>; }
function AnalyticsSkeleton() { return <div className="mx-auto max-w-6xl space-y-5"><div className="h-32 animate-pulse rounded-2xl bg-black/5" /><div className="grid gap-4 sm:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-black/5" />)}</div><div className="h-80 animate-pulse rounded-2xl bg-black/5" /></div>; }
