import { BellRing, MessageCircle, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { notificationsApi, type StudentNotification } from "@/features/notifications/api/notifications.api";
import { messagesApi, type Conversation } from "../api/messages.api";

export function AnnouncementPopup() {
    const [notice, setNotice] = useState<StudentNotification | null>(null);
    const [conversation, setConversation] = useState<Conversation | null>(null);
    const navigate = useNavigate();
    useEffect(() => { void (async () => { const data = await notificationsApi.list(); const next = data.items.find((item) => item.type === "announcement" && item.conversation_id && !item.read_at && !sessionStorage.getItem(`hbt-announcement-${item.id}`)); if (!next) return; setNotice(next); setConversation(await messagesApi.get(next.conversation_id!)); })(); }, []);
    if (!notice || !conversation) return null;
    const dismiss = async () => { sessionStorage.setItem(`hbt-announcement-${notice.id}`, "seen"); await notificationsApi.read(notice.id); setNotice(null); };
    const reply = async (value: string) => { await messagesApi.send(conversation.id, value, "quick_reply"); await dismiss(); navigate(`/messages?conversation=${conversation.id}`); };
    return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#17202b]/30 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-label="New announcement" className="w-full max-w-lg overflow-hidden rounded-[28px] border border-[#3A3A3A]/10 bg-white shadow-2xl"><header className="relative overflow-hidden bg-[#3A3A3A] px-6 py-5 text-white"><div className="absolute -right-10 -top-12 h-32 w-32 rounded-full bg-[#F47822]/25 blur-2xl"/><div className="relative flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#F47822]"><BellRing className="h-5 w-5"/></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#F47822]">New announcement</p><h2 className="mt-1 text-lg font-bold">{notice.title}</h2></div></div><button onClick={() => void dismiss()} className="rounded-lg p-1.5 text-white/60 transition hover:bg-white/10 hover:text-white" aria-label="Dismiss"><X className="h-5 w-5"/></button></div></header><div className="p-6"><p className="whitespace-pre-wrap text-sm leading-6 text-[#3A3A3A]/75">{notice.message}</p>{conversation.replies_enabled && <div className="mt-5"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[#3A3A3A]/42">Quick response</p><div className="mt-2 flex flex-wrap gap-2">{(conversation.quick_replies.length ? conversation.quick_replies : ["Got it", "I have a question"]).map((item) => <button key={item} onClick={() => void reply(item)} className="rounded-full border border-[#F47822]/22 bg-[#F47822]/[.05] px-3 py-2 text-xs font-bold text-[#F47822] transition hover:bg-[#F47822] hover:text-white">{item}</button>)}</div></div>}<div className="mt-6 flex justify-end gap-2"><button onClick={() => void dismiss()} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#3A3A3A]/60">Read later</button><button onClick={async () => { await dismiss(); navigate(`/messages?conversation=${conversation.id}`); }} className="inline-flex items-center gap-2 rounded-xl bg-[#3A3A3A] px-4 py-2.5 text-xs font-bold text-white transition hover:bg-[#F47822]"><MessageCircle className="h-4 w-4"/>Open message</button></div></div></section></div>;
}
